#!/usr/bin/env bash
# Regenerate ~/.config/agent-projects.conf from Loki's user_projects
# table — the actual SSOT for project name/dirPath/agent/model prefs.
#
# WHY THIS EXISTS: agent-projects.conf's own header used to claim "the
# daemon syncs this file". No such sync ever existed in the codebase — it
# was aspirational documentation. A rename or retirement in the DB (Control
# page, or scripts/db/retire-stale-projects.ts) silently left this file
# stale, and every local consumer (home/projects.ts dispatch resolution,
# fleet-runner's watcher) kept reading the old name/path until someone
# noticed and hand-edited it. That's how `revampit|/home/g/dev/revampit`
# outlived the project's rename to `evig` by three weeks, and how
# `swiss-longevity-hub`/`truthseeker-tmp` are still in the file today even
# though retire-stale-projects.ts merged them away in the DB weeks ago.
# This script is the real sync. Run it (or let the installed timer run it —
# see install-agent-projects-sync.sh) and the file matches the DB, always.
#
# Runs the query ON THE BOX over SSH rather than connecting to Postgres
# directly: the DB port has been closed to external connections since the
# 2026-07-17 security audit, reachable only from 127.0.0.1 on the box
# itself. That constraint is permanent, not a workaround — don't "fix" this
# by reopening the port.
#
# Usage:
#   scripts/db/sync-agent-projects-conf.sh            # write ~/.config/agent-projects.conf
#   scripts/db/sync-agent-projects-conf.sh --check     # exit 1 if the file would change; no write
#   AGENT_PROJECTS_CONF=/tmp/x.conf scripts/db/sync-agent-projects-conf.sh   # write elsewhere (testing)
set -euo pipefail

. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../hetzner/_box-env.sh"   # SSOT: BOX_UBUNTU
BOX="${SYNC_AGENT_PROJECTS_BOX:-$BOX_UBUNTU}"
OUT="${AGENT_PROJECTS_CONF:-$HOME/.config/agent-projects.conf}"
CHECK_ONLY=false
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=true

sql_file="$(mktemp)"
tmp_out="$(mktemp)"
trap 'rm -f "$sql_file" "$tmp_out"' EXIT

cat > "$sql_file" <<'SQL'
select up.name || '|' || up.dir_path || '|' || coalesce(up.agent_pref, '') || '|' || coalesce(up.model_pref, '')
from user_projects up
where up.is_active = true and up.dir_path is not null
order by up.position, up.name;
SQL

rows="$(ssh -o ConnectTimeout=10 "$BOX" \
  'sudo bash -c "set -a; . /opt/loki/app/.env; set +a; psql -At \"\$DATABASE_URL\""' \
  < "$sql_file" 2>/dev/null)" || {
  echo "sync-agent-projects-conf: could not reach $BOX or query failed — leaving $OUT untouched" >&2
  exit 1
}

if [[ -z "$rows" ]]; then
  echo "sync-agent-projects-conf: empty result from DB query — refusing to overwrite $OUT" >&2
  exit 1
fi

{
  echo "# Generated by loki/scripts/db/sync-agent-projects-conf.sh from the"
  echo "# Loki user_projects table — the SSOT. Do not hand-edit; rename or"
  echo "# retire projects via the Control page, then re-run the sync."
  echo "# Format: tab_name|/absolute/path/to/project|agent|model"
  echo "$rows"
} > "$tmp_out"

missing=0
while IFS='|' read -r name dir _rest; do
  [[ -z "$name" || "$name" == \#* ]] && continue
  if [[ -n "$dir" && ! -d "$dir" ]]; then
    echo "⚠ $name → $dir does not exist on disk (stale registry entry?)" >&2
    missing=$((missing + 1))
  fi
done < "$tmp_out"

if diff -q "$tmp_out" "$OUT" >/dev/null 2>&1; then
  echo "up to date ($(grep -vc '^#' "$tmp_out") projects, $missing missing on disk)"
  exit 0
fi

if $CHECK_ONLY; then
  echo "would rewrite $OUT ($(grep -vc '^#' "$tmp_out") projects, $missing missing on disk)"
  exit 1
fi

chmod 600 "$tmp_out"
mv "$tmp_out" "$OUT"
echo "wrote $OUT ($(grep -vc '^#' "$OUT") projects, $missing missing on disk)"
