/**
 * GENERATED by scripts/generate-fleet-sites.ts from scripts/hetzner/apps.conf.
 * Do not edit: scripts/test/fleet-sites-derived.ts fails when this drifts.
 * Copy lives in src/config/fleet-site-copy.ts; the LIST lives in apps.conf.
 *
 * Why derived: the hand-kept version named a host that had been renamed and
 * missed twelve live ones. A list nobody regenerates is a list that lies.
 */
export type FleetSite = {
  /** The site's own name, as it titles itself. */
  name: string;
  url: string;
  /** One line, condensed from the site's own meta description. */
  blurb: string;
};

/** Ordered by name. Loki itself is absent on purpose. */
export const FLEET_SITES: readonly FleetSite[] = [
  {
    name: "AOZ Begleitung",
    url: "https://aoz.orangecat.ch",
    blurb: "Gemeinsam wohnen — kompatibilitätsbasierte Wohnplatzierung.",
  },
  {
    name: "Botsmann",
    url: "https://botsmann.orangecat.ch",
    blurb: "Private AI that works with your own documents.",
  },
  {
    name: "causius",
    url: "https://causius.orangecat.ch",
    blurb: "",
  },
  {
    name: "datacat",
    url: "https://datacat.orangecat.ch",
    blurb: "KI-gestützter Formular-Editor für jede Branche.",
  },
  {
    name: "evig",
    url: "https://evig.orangecat.ch",
    blurb: "Refurbished IT kaufen und Reparaturwerkstätten finden.",
  },
  {
    name: "Heidi",
    url: "https://heidi.orangecat.ch",
    blurb: "Züritüütsch verstehen, dann wie ein Local texten. Im Aufbau.",
  },
  {
    name: "kivvi",
    url: "https://kivvi.orangecat.ch",
    blurb: "Open-Source-ERP für Kreislaufbetriebe.",
  },
  {
    name: "Petvity",
    url: "https://petvity.orangecat.ch",
    blurb: "Track your pet's health, vets, sitters and essentials.",
  },
  {
    name: "revamp.info",
    url: "https://revamp-info.orangecat.ch",
    blurb: "Transparentes Fundraising: Finanzen, Wirkung, Strategie.",
  },
  {
    name: "S-Ink Tattoo",
    url: "https://sinktattoo.com",
    blurb: "Tattoo studio in Zürich.",
  },
  {
    name: "Solon",
    url: "https://solon.orangecat.ch",
    blurb: "Bitcoin-native governance for the digital age.",
  },
  {
    name: "Substrata",
    url: "https://substrata.orangecat.ch",
    blurb: "Open research on the physical chokepoints between here and a singularity.",
  },
  {
    name: "Surf Your Life",
    url: "https://surf-your-life.orangecat.ch",
    blurb: "Psychiatry-led burnout recovery in Zürich.",
  },
  {
    name: "Vita",
    url: "https://vitareba.orangecat.ch",
    blurb: "Metabolische Psychiatrie und systemische Longevity, Zürich.",
  },
];
