/**
 * The widget's copy of the Loki spiral, derived from the brand-mark SSOT.
 *
 * The widget is a separate bundle that may not import from src/
 * (scripts/test/widget-self-contained.ts), so — like its theme — the mark is
 * GENERATED into widget/ rather than redrawn there. Fewer samples than the
 * full mark: it is drawn at 14–18px, where 48 points per turn is already
 * smooth and keeps the embed small.
 *
 *   npx tsx scripts/generate-widget-brand-mark.ts          # write
 *   npx tsx scripts/generate-widget-brand-mark.ts --check  # exit 1 if stale
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { BRAND_MARK, spiralPathD } from "../src/config/brand-mark";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "widget", "brand-mark.generated.ts");

export function generate(): string {
  const d = spiralPathD({ samplesPerTurn: 48 });
  return [
    "// GENERATED by scripts/generate-widget-brand-mark.ts from src/config/brand-mark.ts.",
    "// Do not edit — change the brand mark and regenerate.",
    "",
    `export const SPIRAL_VIEWBOX = ${BRAND_MARK.viewBox};`,
    `export const SPIRAL_STROKE = ${BRAND_MARK.strokeWidth};`,
    `export const SPIRAL_D =\n  "${d}";`,
    "",
  ].join("\n");
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const next = generate();
  if (process.argv.includes("--check")) {
    const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
    if (current !== next) {
      console.error("widget/brand-mark.generated.ts is stale — run the generator");
      process.exit(1);
    }
  } else {
    writeFileSync(OUT, next);
    console.log(`wrote ${OUT}`);
  }
}
